### PR TITLE
Support for configuring envoy connection parameters in ingress, which istio currently supports.

### PR DESCRIPTION
**Pull request by shengyanli1982**
# Changes

configuring envoy connection parameters from ingress annotations resource by user defined

/kind enhancement

Fixes #

**Release Note**

```release-note
The current project only use default values envoy connection parameters and are not configured for connections to clusters created by ingress. now, can configuring envoy connection parameters from ingress annotations resource by user defined.
```

**Unit Test**

```Test
=== RUN   TestIngressTranslator
--- PASS: TestIngressTranslator (0.04s)
=== RUN   TestIngressTranslator/simple
    --- PASS: TestIngressTranslator/simple (0.01s)
=== RUN   TestIngressTranslator/tls
    --- PASS: TestIngressTranslator/tls (0.01s)
=== RUN   TestIngressTranslator/tls_redirect
    --- PASS: TestIngressTranslator/tls_redirect (0.01s)
=== RUN   TestIngressTranslator/tls_redirect_cluster_local
    --- PASS: TestIngressTranslator/tls_redirect_cluster_local (0.00s)
=== RUN   TestIngressTranslator/split
    --- PASS: TestIngressTranslator/split (0.01s)
=== RUN   TestIngressTranslator/path_defaulting
    --- PASS: TestIngressTranslator/path_defaulting (0.00s)
=== RUN   TestIngressTranslator/external_service
    --- PASS: TestIngressTranslator/external_service (0.00s)
=== RUN   TestIngressTranslator/external_service_without_service_port
    --- PASS: TestIngressTranslator/external_service_without_service_port (0.00s)
=== RUN   TestIngressTranslator/missing_service
{"level":"warn","ts":1657538878.371255,"logger":"fallback","caller":"generator/ingress_translator.go:193","msg":"Service 'servicens/servicename' not yet created"}
    --- PASS: TestIngressTranslator/missing_service (0.00s)
=== RUN   TestIngressTranslator/missing_endpoints
{"level":"warn","ts":1657538878.371395,"logger":"fallback","caller":"generator/ingress_translator.go:236","msg":"Endpoints 'servicens/servicename' not yet created"}
    --- PASS: TestIngressTranslator/missing_endpoints (0.00s)
PASS
```

**Envoy Config Dump**
```
"circuit_breakers": {
    "thresholds": [
     {
      "max_connections": 4294967295,
      "max_pending_requests": 4294967295,
      "max_requests": 4294967295,
      "max_retries": 10
     },
     {
      "priority": "HIGH",
      "max_connections": 4294967295,
      "max_pending_requests": 4294967295,
      "max_requests": 4294967295,
      "max_retries": 10
     }
    ]
}
```

### CODE REVIEW

**Comment by dprotaso** [comment]
/assign @nak3 
/unassign @dprotaso 

Not familiar with kourier enough to review this

**Comment by shengyanli1982** [comment]
> Could you please describe what exact problems did you encounter with the current values?

Of course. We used Net-Kourier + Kourier as the gateway for our backend knatvie applications. In the real world, we have a service with the concurrency mode between 10 and 60 pods. We are an e-commerce business, so the peak of requests will often be like a wave, and the enovy default of 1000 will often be stuck to our peak requests.

Our internal version has been modified and confirmed to be able to effectively support online services.

**Comment by nak3** [comment]
Thank you for the explanation and sorry for the late response.
Could you please clean up the PR? I think there are some unexpected change in the PR.

Also, if possible I would like to avoid the annotation approach. Did you consider any alternative idea to support this without the annotation?

**Comment by shengyanli1982** [comment]
Emm and INGress forwards traffic for a service. A service has a service attribute. Ingress is also a CRD resource, so these contents naturally have a clear mapping relationship. Annotation is where I can think of the most efficient way to extend custom attributes, maybe you have a better idea.

In the real world, we use Labels to distinguish different services and business types, Annotation as an application public metadata attribute definition, and Env to define variables within different versions of POD. Clear data definition layering facilitates large-scale POD operation and management.

The above content is for your reference only.

**Comment by mbrancato** [comment]
@nak3 what would be needed to get this to a state where it can be merged? If this is no longer being worked on, I could takeover this and get it to a mergable state. If you need more info on the use-case, I too have an issue linked below that this addresses.

Fixes #839

**Comment by skonto** [comment]
@shengyanli1982  could rebase the PR? gentle ping.

**Comment by skonto** [comment]
@shengyanli1982 could rebase the PR? gentle ping.

**Comment by skonto** [comment]
@mbrancato could you help on this one?

**Pull request closed without merging**
