### PR TITLE
Increase kourier controller CPU limit

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Increases the CPU limits of net-kourier controller to avoid slow startup with ~500 KSVCs

**Release Note**

```release-note
The CPU limit of kourier controller was increased to avoid CPU limitation issues in larger installations
```

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

But will we backport this to 1.10 and other branches on upstream? I wonder that we should backport it into our downstream instead of creating the new releases i.e. v1.11.6, v1.10.4 etc. I don't have strong objections but just wanted to confirm.

**Comment by ReToCode** [comment]
> But will we backport this to 1.10 and other branches on upstream? I wonder that we should backport it into our downstream instead of creating the new releases i.e. v1.11.6, v1.10.4 etc. I don't have strong objections but just wanted to confirm.

Valid point, let's do that then, I'll close the PRs that will be opened.

/unhold

**Comment by ReToCode** [comment]
@nak3 I did keep the 1.12 back-port, as this version will be here for a while, and then we can upstream-sync easier.

**Pull request merged**
