### PR TITLE
Use aligned flags and secrets for `system-internal-tls`

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Uses the aligned flags from https://github.com/knative/serving/issues/14368
- Uses the new secrets & SANs from https://github.com/knative/serving/issues/14369

/kind cleanup

Partially https://github.com/knative/serving/issues/14369
Partially https://github.com/knative/serving/issues/14392
Partially https://github.com/knative/serving/issues/14368

**Release Note**

```release-note
net-kourier now uses the new `system-internal-tls` flag to configure encryption of Knative system components.
```

**Docs**
Will be done separately when encryption is working end-to-end

### CODE REVIEW

**Comment by nak3** [comment]
/hold

Ah, `Code Style / style / Golang / Lint` should be fixed.

**Comment by ReToCode** [comment]
We also need to create the new certificates with SANs in the script. 
For now we do not use all of them, but I think it is better to have the correct secrets with SANs that we are going to use in Serving, so we can build on top of that when adding the `cluster-local-domain-tls` stuff.

**Comment by ReToCode** [comment]
/unhold
@nak3

**Pull request merged**
