### PR TITLE
Increase gateway memory limit

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Increase 3scale-kourier-gateway memory limit

Fixes https://github.com/knative/serving/issues/15052

**Release Note**
```release-note
The default memory limit of 3scale-kourier-gateway was increased to prevent OOMKilled on peak load scenarios
```

### CODE REVIEW

**Comment by ReToCode** [comment]
/assign @skonto 

Tested in https://github.com/knative/serving/pull/15060.

**Comment by skonto** [comment]
Do we know why we need this increase, what is the root cause of the overhead?

**Comment by ReToCode** [comment]
That we added more stuff to encryption, we are definitely creating more envoy config with this (thus, just the tls test were flaky).

**Pull request merged**
